version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build phase"
      - mkdir -p /dist  # Create /dist directory if it doesn't exist
      - cp index.html /dist/index.html

artifacts:
  files: /dist/**
